const categories = {
    "books": [
        { title: "The Great Gatsby", price: "$10.99", description: "A classic novel by F. Scott Fitzgerald.", images: ["https://m.media-amazon.com/images/I/81af+MCATTL._AC_UL480_QL65_.jpg"], rating: 4.7 },
        { title: "1984", price: "$8.99", description: "A dystopian novel by George Orwell.", images: ["https://m.media-amazon.com/images/I/71kxa1-0mfL._AC_UL480_QL65_.jpg"], rating: 4.8 },
        { title: "To Kill a Mockingbird", price: "$9.99", description: "A novel by Harper Lee about racial injustice.", images: ["https://m.media-amazon.com/images/I/71uRX75k8TL._AC_UY327_FMwebp_QL65_.jpg"], rating: 4.9 },
        { title: "Moby Dick", price: "$12.50", description: "A novel by Herman Melville about a whaling voyage.", images: ["https://m.media-amazon.com/images/I/81wgcld4wxL._AC_UL480_QL65_.jpg"], rating: 4.6 },
        { title: "War and Peace", price: "$15.99", description: "A novel by Leo Tolstoy about historical Russia.", images: ["https://m.media-amazon.com/images/I/714nPivK1oL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.8 },
        { title: "Pride and Prejudice", price: "$10.99", description: "A romance novel by Jane Austen.", images: ["https://m.media-amazon.com/images/I/91bYsX41DVL._AC_UL480_QL65_.jpg"], rating: 4.7 },
        { title: "The Catcher in the Rye", price: "$11.99", description: "A novel by J.D. Salinger.", images: ["https://m.media-amazon.com/images/I/71rNJQ2g-EL._AC_UL480_QL65_.jpg"], rating: 4.6 },
        { title: "Brave New World", price: "$9.99", description: "A dystopian novel by Aldous Huxley.", images: ["https://m.media-amazon.com/images/I/71GNqqXuN3L._AC_UY327_FMwebp_QL65_.jpg"], rating: 4.8 },
        { title: "Crime and Punishment", price: "$14.99", description: "A psychological novel by Fyodor Dostoevsky.", images: ["https://m.media-amazon.com/images/I/615ApZul7gL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.7 },
        { title: "The Hobbit", price: "$13.99", description: "A fantasy novel by J.R.R. Tolkien.", images: ["https://m.media-amazon.com/images/I/91b0C2YNSrL._AC_UL480_QL65_.jpg"], rating: 4.9 }],
    "fashion-clothing": [
        { title: "Casual T-Shirt", price: "$15.99", description: "Comfortable and stylish cotton T-shirt.", images: ["https://m.media-amazon.com/images/I/71ufhuS2oOL._AC_SX569_.jpg"], rating: 4.5 },
        { title: "Denim Jacket", price: "$49.99", description: "Classic blue denim jacket for all occasions.", images: ["https://m.media-amazon.com/images/I/81lvCEYX2LL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.7 },
        { title: "Slim Fit Jeans", price: "$39.99", description: "Trendy slim fit jeans for daily wear.", images: ["https://m.media-amazon.com/images/I/71ImLCRn1NL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.6 },
        { title: "Formal Shirt", price: "$29.99", description: "Perfect for office and formal events.", images: ["https://m.media-amazon.com/images/I/61MKDbVijyL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.8 },
        { title: "Sports Hoodie", price: "$35.99", description: "Warm and comfortable hoodie for workouts.", images: ["https://m.media-amazon.com/images/I/71HiXFsXOsL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.7 },
        { title: "Athletic Sneakers", price: "$59.99", description: "Lightweight and durable sneakers.", images: ["https://m.media-amazon.com/images/I/81Wbmd-PArL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.9 },
        { title: "Leather Belt", price: "$19.99", description: "High-quality genuine leather belt.", images: ["https://m.media-amazon.com/images/I/61BrX3X0IuL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.6 },
        { title: "Wool Scarf", price: "$25.99", description: "Soft wool scarf for winter.", images: ["https://m.media-amazon.com/images/I/81s0LPo+pgL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.7 },
        { title: "Sunglasses", price: "$14.99", description: "Stylish UV protection sunglasses.", images: ["https://m.media-amazon.com/images/I/61-JdOE8J1L._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.8 },
        { title: "Baseball Cap", price: "$12.99", description: "Adjustable cotton baseball cap.", images: ["https://m.media-amazon.com/images/I/71WBhEyyQYL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.5 }],
    "health-personal-care": [
        { title: "Multivitamin Supplements", price: "$19.99", description: "Daily essential vitamins for overall health.", images: ["https://m.media-amazon.com/images/I/61-KuuYB73L._AC_UL480_QL65_.jpg"], rating: 4.6 },
        { title: "Herbal Shampoo", price: "$9.99", description: "Natural ingredients for healthy hair.", images: ["https://m.media-amazon.com/images/I/81JivqfoJjL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.5 },
        { title: "Electric Toothbrush", price: "$29.99", description: "Advanced plaque removal technology.", images: ["https://m.media-amazon.com/images/I/81Iq+LsctsL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.7 },
        { title: "Organic Aloe Vera Gel", price: "$12.50", description: "Soothing gel for skin hydration.", images: ["https://m.media-amazon.com/images/I/81igfHZd8ZL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.8 },
        { title: "Protein Powder", price: "$39.99", description: "High-quality whey protein for muscle growth.", images: ["https://m.media-amazon.com/images/I/81r0ygjRbLL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.6 },
        { title: "Face Moisturizer", price: "$14.99", description: "Hydrating cream with SPF protection.", images: ["https://m.media-amazon.com/images/I/71Qm8sr7zhL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.5 },
        { title: "Essential Oil Set", price: "$24.99", description: "Aromatherapy oils for relaxation.", images: ["https://m.media-amazon.com/images/I/81YZ9rBf+sL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.8 },
        { title: "Hair Growth Serum", price: "$18.99", description: "Strengthens and nourishes hair follicles.", images: ["https://m.media-amazon.com/images/I/61vE4uQg+PL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.7 },
        { title: "Body Scrub", price: "$11.99", description: "Exfoliating scrub with natural ingredients.", images: ["https://m.media-amazon.com/images/I/81higV9zmNL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.6 },
        { title: "Massage Gun", price: "$99.99", description: "Deep tissue massage for muscle recovery.", images: ["https://m.media-amazon.com/images/I/61bKIX--tzL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.9 }],
    "shopper-toolkit": [
        { title: "DIY Toolset", price: "$39.99", description: "Essential tools for home repairs.", images: ["https://m.media-amazon.com/images/I/71DwK47GTkL._AC_UL480_QL65_.jpg"], rating: 4.5 },
        { title: "Cordless Drill", price: "$89.99", description: "Powerful drill for all projects.", images: ["https://m.media-amazon.com/images/I/61oeYCtViNL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.7 },
        { title: "Screwdriver Set", price: "$24.99", description: "Precision screwdrivers for repairs.", images: ["https://m.media-amazon.com/images/I/71qM90IukeL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.6 },
        { title: "Hammer", price: "$15.99", description: "Durable hammer for household tasks.", images: ["https://m.media-amazon.com/images/I/31BgeyAS3DS._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.5 },
        { title: "Measuring Tape", price: "$9.99", description: "Retractable tape measure.", images: ["https://m.media-amazon.com/images/I/71ZQtIeBo+L._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.6 },
        { title: "Pliers Set", price: "$29.99", description: "Variety of pliers for gripping.", images: ["https://m.media-amazon.com/images/I/61Iq+sp023L._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.7 },
        { title: "Utility Knife", price: "$12.99", description: "Razor-sharp utility knife.", images: ["https://m.media-amazon.com/images/I/71xBHTlLvyL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.5 },
        { title: "Wrench Set", price: "$49.99", description: "Adjustable wrench set.", images: ["https://m.media-amazon.com/images/I/81w8rek+ScL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.8 },
        { title: "Level Tool", price: "$19.99", description: "Bubble level for precise alignment.", images: ["https://m.media-amazon.com/images/I/511lJu1mSvL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.6 },
        { title: "Stud Finder", price: "$25.99", description: "Detect studs in walls.", images: ["https://m.media-amazon.com/images/I/71T6IEDQvCL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.7 }
    ],
    "food-grocery": [
        { title: "Organic Apple", price: "$5.99", description: "Fresh organic apples.", images: ["https://m.media-amazon.com/images/I/81AK2aQ8VvL._AC_UL480_QL65_.jpg"], rating: 4.7 },
        { title: "Whole Wheat Bread", price: "$3.99", description: "Healthy whole grain bread.", images: ["https://m.media-amazon.com/images/I/81Q-K+o40ML._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.6 },
        { title: "Almond Milk", price: "$4.99", description: "Dairy-free almond milk.", images: ["https://m.media-amazon.com/images/I/71kqyMB+tAL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.7 },
        { title: "Brown Rice", price: "$8.99", description: "Organic brown rice.", images: ["https://m.media-amazon.com/images/I/71R2cPcXOZL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.6 },
        { title: "Peanut Butter", price: "$6.99", description: "Creamy peanut butter.", images: ["https://m.media-amazon.com/images/I/61lESWFq0HL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.7 },
        { title: "Olive Oil", price: "$10.99", description: "Extra virgin olive oil.", images: ["https://m.media-amazon.com/images/I/51bTxOyUqcL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.8 },
        { title: "Organic Eggs", price: "$7.99", description: "Farm-fresh organic eggs.", images: ["https://m.media-amazon.com/images/I/71HkLYMxxeL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.9 },
        { title: "Greek Yogurt", price: "$5.49", description: "High protein Greek yogurt.", images: ["https://m.media-amazon.com/images/I/51ZpvEbmt6L._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.8 },
        { title: "Dark Chocolate", price: "$3.99", description: "Premium dark chocolate.", images: ["https://m.media-amazon.com/images/I/51YEodhQ-vL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.7 },
        { title: "Mixed Nuts", price: "$12.99", description: "Healthy mixed nuts pack.", images: ["https://m.media-amazon.com/images/I/81l3Yq0sFcL._AC_UL480_FMwebp_QL65_.jpg"], rating: 4.8 }
    ],
    "electronics": [
        { title: "Wireless Noise Cancelling Headphones", price: "$299.99", description: "Active noise cancellation.", images: ["https://m.media-amazon.com/images/I/610DB8Cwm7L._AC_UY327_QL65_.jpg"], rating: 4.5 },
        { title: "Smartphone Pro Max", price: "$999.99", description: "Latest smartphone with high-end features.", images: ["https://m.media-amazon.com/images/I/71xb2xkN5qL._AC_SL1500_.jpg"], rating: 4.8 },
        { title: "Wireless Keyboard", price: "$49.99", description: "Silent keyboard for work.", images: ["https://m.media-amazon.com/images/I/61urVxLeYPL._AC_UY327_QL65_.jpg"], rating: 4.6 },
        { title: "Smartwatch", price: "$199.99", description: "Fitness and health tracking smartwatch.", images: ["https://m.media-amazon.com/images/I/71SZNup1qrL._AC_UY327_FMwebp_QL65_.jpg"], rating: 4.7 },
        { title: "Gaming Laptop", price: "$1499.99", description: "High-performance gaming laptop.", images: ["https://m.media-amazon.com/images/I/71ckTjPAG0L._AC_UY327_FMwebp_QL65_.jpg"], rating: 4.8 },
        { title: "4K Ultra HD TV", price: "$699.99", description: "Crystal clear 4K television.", images: ["https://m.media-amazon.com/images/I/61hhulNlPYL._AC_UY327_FMwebp_QL65_.jpg"], rating: 4.7 },
        { title: "Bluetooth Speaker", price: "$59.99", description: "Portable high-quality sound.", images: ["https://m.media-amazon.com/images/I/61Dq66zEttL._AC_UY327_FMwebp_QL65_.jpg"], rating: 4.6 },
        { title: "External Hard Drive", price: "$89.99", description: "1TB storage capacity.", images: ["https://m.media-amazon.com/images/I/611LbnyTYNL._AC_UY327_FMwebp_QL65_.jpg"], rating: 4.7 },
        { title: "Wireless Mouse", price: "$25.99", description: "Ergonomic wireless mouse.", images: ["https://m.media-amazon.com/images/I/61LtuGzXeaL._AC_SL1500_.jpg"], rating: 4.6 },
        { title: "Smart Home Camera", price: "$129.99", description: "AI-powered security camera.", images: ["https://m.media-amazon.com/images/I/31k4JysPQ5L._AC_UY327_FMwebp_QL65_.jpg"], rating: 4.8 }],
};

export default categories;
